name: water_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  csv: ^5.0.1
  rounded_loading_button: ^2.0.8
  get_storage: ^2.1.1
  path_provider: ^2.0.14
  file_picker: ^5.2.10

  flutter:
    sdk: flutter
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
